# Generated by Django 4.2 on 2023-04-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=89)),
                ('lname', models.CharField(max_length=88)),
                ('Username', models.CharField(max_length=80)),
                ('pass1', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=120)),
                ('specialization', models.CharField(max_length=180)),
            ],
        ),
    ]
