# Generated by Django 4.2 on 2023-04-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_doctorinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('symptom1', models.CharField(max_length=120)),
                ('symptom2', models.CharField(max_length=120)),
                ('symptom3', models.CharField(max_length=120)),
                ('symptom4', models.CharField(max_length=120)),
                ('symptom5', models.CharField(max_length=120)),
                ('predicted_disease', models.CharField(max_length=120)),
                ('consultdoctor', models.CharField(max_length=120)),
            ],
        ),
    ]
