# Generated by Django 4.2 on 2023-04-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_reportd'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientdec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaarno', models.CharField(default='', max_length=25)),
                ('name', models.CharField(max_length=190)),
                ('lname', models.CharField(max_length=190)),
                ('symptoms1', models.CharField(max_length=200)),
                ('symptoms2', models.CharField(max_length=200)),
                ('symptoms3', models.CharField(max_length=200)),
                ('symptoms4', models.CharField(max_length=200)),
                ('Disease', models.CharField(max_length=200)),
                ('Medicine', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=200)),
                ('hphone', models.CharField(max_length=10)),
                ('pdf', models.FileField(default=None, max_length=1000, null=True, upload_to='document/')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaarno', models.CharField(default='', max_length=10)),
                ('fname', models.CharField(max_length=89)),
                ('lname', models.CharField(max_length=88)),
                ('email', models.EmailField(max_length=90)),
                ('pass1', models.CharField(max_length=90)),
                ('pass2', models.CharField(max_length=90)),
            ],
        ),
    ]
