# Generated by Django 4.2 on 2023-04-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_patientdec_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdec',
            name='pdf',
        ),
        migrations.AddField(
            model_name='patientdec',
            name='file',
            field=models.FileField(default='0', upload_to='document/'),
        ),
    ]
